### ISSUE TITLE
Clean out the GitHub Repo

### ISSUE THREAD

**Issue by MarrelleBailey** [solid/team#11]

**Comment by theRealImy** [comment]
From what I remember @RubenVerborgh did this task last year...

**Comment by RubenVerborgh** [comment]
?

**Comment by theRealImy** [comment]
Oh my mistake, I think it was @justinwb 😓

**Comment by bourgeoa** [comment]
I think @RubenVerborgh proved it was doable.
But the task needs some inventory.

**Comment by RubenVerborgh** [comment]
Finalizing this in https://github.com/solid/team/issues/22
