### ISSUE TITLE
Change Solid logo back to normal purple version

### ISSUE THREAD

**Issue by KyraAssaad** [solid/team#17]
Needs to be changed on:

- [x] Twitter - @MarrelleBailey 
- [x] This Month in Solid newsletter - @MarrelleBailey 
- [x] Solid Forums - @justinwb 
- [x] Solid Gitter - @justinwb

**Comment by megoth** [comment]
AFAICT this has been resolved? I'm closing it for now, but please reopen if I'm mistaken.

**Comment by megoth** [comment]
AFAICT this has been resolved? I'm closing it for now, but please reopen if I'm mistaken.

**Comment by megoth** [comment]
Then it should be resolved ^_^ (Justin helped me with the change in the forum, so many thanks to him)

I'll close the issue for now, but let me know if I'm mistaken.
