### ISSUE TITLE
Applying the proposed guidelines to repositories under github.com/solid

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/team#22]
At the [previous Solid Team meeting](https://github.com/solid/team/blob/main/meetings/2022-03-09.md#github-repository-cleanup), we agreed that only Solid Team-managed repositories should live under _github.com/solid_.
We agreed to move out all other repositories to separate organizations.

Below is a checklist to apply the above decision, for which I'd like your approval.

- [x] Propose repository inclusion criteria: https://github.com/solid/process/pull/276
- [x] Have the inclusion text approved by the team (done in meeting of 2022/04/13)
- [x] Make a list of repositories that need to be moved under these criteria: https://github.com/solid/team/issues/24
  - This includes project/code/examples from editors, creators, administrators, etc.
- [x] For each repository in this list
  - [x] If archived, move to https://github.com/solid-contrib/
  - [x] If not archived, create an issue with the text below
  - [x] If not moved after 2 weeks, move to https://github.com/solid-contrib/ from where it can be moved further if needed
- [x] Update the list at https://github.com/orgs/solid/people
- [ ] Maintain a list of Solid repositories on solidproject.org

---

## Proposed issue text

Issue title: Re-organizing github.com/solid

<br>

Dear repository maintainer,

On behalf of the Solid Team, thanks for creating resources for the Solid project. We appreciate your efforts!

### A new vision on the github.com/solid namespace

We want to give all projects the spotlights they deserve, and that's why we have taken the decision to **re-envision what the _github.com/solid_ namespace will contain** going forward.

Today, it is a mix of documents that are authoritative to Solid (such as specifications and processes), and software code in various stages of completion, some of which date back to when Solid was an MIT project.

**Starting May 2022,  _github.com/solid_ will be a space for the authoritative documents**, as described in the [process repository](https://github.com/solid/process/blob/fbc26beabd84a94167458e3be845dce02878ebd2/repositories.md).

### Please help us by moving this repository

For that reason, **we kindly ask you to move this repository to a different GitHub organization**. This could be your personal GitHub username, or an organization that bundles several of your Solid projects. The choice is entirely yours.

Please let us know what you decide, so we can link to your repositories in the future. Rest assured that the existing link will keep on working; GitHub will redirect it to its new place. If you need any help with the migration, we'll be happy to assist.

Repositories that have not been moved by 1 May 2022 will be moved automatically to https://github.com/solid-contrib/, from where you can still make the decision to move them to another place at a later point in time.

Thanks in advance for your help!

Kind regards,

The Solid Team

**Comment by justinwb** [comment]
Checklist: 👍 
Proposed issue text: 👍 
Explicit date (April 15th): 👍  (assuming this is approved in time that people have at least two weeks to respond)

**Comment by kjetilk** [comment]
I think it is very worthwhile to clean up the repository, as it is very confusing. I think solid-contrib is a good idea, but I don't understand what makes solid-archive valuable, as archived repositories are clearly marked as such in the list of repositories and will not get the same prominence. When archived, they already have the metadata required that was asked for by @timbl in the original issue, and the UI is there to support it.

**Comment by RubenVerborgh** [comment]
> I don't understand what makes solid-archive valuable

Actually, I can equally move those to `solid-contrib`. Or perhaps the other way round; `solid-contrib` can not be used and everything can be moved to `solid-archive` instead, and we still have the _archived_ metadata bit to add.

> when archived, they already have the metadata required that was asked for by timbl in the original issue

Yes; but the team discussion was slightly different than that issue.

**Comment by bourgeoa** [comment]
> Implementations are not neutral; they make certain decisions regarding implementations.

This imply removing all solid history and relation between implementation and specification.
This is quite a harsh step. Clarification is good, but making it a white page has some signification.

This remove auth, namespace, nss, mashlib, solidcommunity.net, tests ...

In a way this disregard the effort made by community contributors to solid by way of implementations and not only to specification.

Does `solid/team` do not cover some form of community management ?
Does `solid-contrib` reflects the community involvement ? Be it university contributions or individuals ... ?

**Comment by kjetilk** [comment]
I agree that we shouldn't be picking favorites, but I also think that it is over the top to remove all that, this is a community after all.

I think we shouldn't say that a place in the Solid org implies endorsement, only that it is a valid contribution, and so the Team would then need to define what a valid contributions is.

**Comment by RubenVerborgh** [comment]
> This remove auth, namespace, nss, mashlib, solidcommunity.net, tests ...

Not namespace or solidcommunity.net.

But yes auth, NSS, Mashlib, tests. They are all opinionated.

> In a way this disregard the effort made by community contributors to solid by way of implementations and not only to specification.

> In a way this disregard the effort made by community contributors to solid by way of implementations and not only to specification.

I don't see how. It's not a value judgment.
Just a recognition that it would be unfair to promote some implementations over others.

Now, we are selectively promoting some implementers but not others.

> I think we shouldn't say that a place in the Solid org implies endorsement,

We do not decide that though. It's what people see.

---

@kjetilk @bourgeoa May I please ask to move this discussion to https://github.com/solid/process/pull/276? The scope of this proposal is discussed there. This is a discussion of the action plan once there is agreement on scope.

**Comment by kay-kim** [comment]
One minor thing (and it may be nothing, so feel free to disregard), but I wonder if we could be a smidge clearer about the site reorg since we state that we want the site to host authoritative documents and we link to a process where the various Solid teams (editors, creators, administrators) are a bit heavy with Inrupt people.  I feel like this could lead people to conclude the content will lean towards Inrupt when that is not what we're trying to do.

**Comment by csarven** [comment]
I think we should keep some of the spec tests repos remain under solid org. We need the tests to be authoritative and neutral from the CG's perspective. If we move them out of solid/ we lose a bit of that credibility long term. solid-contrib is a reasonable but temporary solution. However, that still feels a bit strange org where the tests can live on.

We need the specs to link to the tests and implementation reports that's in neutral space - preferably managed by a group.

I say as someone that took on the hosting and management of the LDN tests (under linkedresearch.org ) and at the time the WG was okay with that. I don't think the Chairs should've allowed that to happen. Because right now the spec links to it, I control the domain, hosting, tool etc.. including the reports. In a long enough timeline, I will get hit by a bus.

Just as the spec repos are under the solid org, so should their tests/reports that are acknowledged by the CG. If we just need to call out what's approved/authoritative from the CG's perspective, we can do that - that's where we need to be in any case. Then the key tests can remain under solid org and the rest - if not associated with a spec that's listed as a Work Item under https://solidproject.org/TR/ , then they can move out. We can in fact do that today.

**Comment by RubenVerborgh** [comment]
> We need the tests to be authoritative and neutral from the CG's perspective.

100% agree.
But until that is the case, I would temporarily move them out of `/solid`, such that everything under here is authoritative.

> solid-contrib is a reasonable but temporary solution.

Emphasis on _temporary_ indeed. However, I sincerely hope that the tests _do not_ end up there; that's only a last resort if test suite maintainers choose to not create separate organizations for their tests.

> If we just need to call out what's approved/authoritative from the CG's perspective, we can do that - that's where we need to be in any case.

My proposal is the other way round: let's move test _into_ `/solid` when they are approved. So this move is temporary.

**Comment by kjetilk** [comment]
> > If we just need to call out what's approved/authoritative from the CG's perspective, we can do that - that's where we need to be in any case.
> 
> My proposal is the other way round: let's move tests _into_ `/solid` when they are approved. So this move is temporary.

I think moving back and forth will be confusing, I would not think that would be a great service to the community.

Moreover, the conformance test suite does this the right way already, it indicates in the test description what the status of a test is. Whether a test has been approved is noted on a very detailed level and can be used by the toolchain (and is already being used). This is a much better way of doing it than relying on moving it around temporarily.

Other than that, I can live with solid-contrib if we can ensure that it does not incur too much cost in administration of accesses.

**Comment by RubenVerborgh** [comment]
All moves have been performed.

**Comment by RubenVerborgh** [comment]
Also updated https://github.com/orgs/solid/people to match the list of repositories. Administrators are duplicated at solid-contrib.

**Comment by jaxoncreed** [comment]
I believe the only thing left to do on this task is update the Solid Website. @jeff-zucker is that something you can do?

**Comment by timea-solid** [comment]
> I believe the only thing left to do on this task is update the Solid Website. @jeff-zucker is that something you can do?

This task is done. The remaining task has its own ticket now: https://github.com/solid/team/issues/23#issuecomment-1379426860
Last year we said we are going to mention that on the website with pointers to repos. @jeff-zucker  too the action last year. 
So this ticket can be closed form my point of view.
