### ISSUE TITLE
Set up a space to link to existing implementations

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/team#23]
We should set up a space that links to _all_ existing implementations (not just the ones under _github.com/solid_).
This could be on GitHub or on solidproject.org.

**Comment by kjetilk** [comment]
Yup! It sounds like a good dogfooding thing to do when we are running solidproject.org on CSS. We should have RDF metadata about implementations that people can suggest additions to, and then have a list rendered with faceted search and stuff.

**Comment by csarven** [comment]
https://github.com/solid/specification/issues/383 is intended to have an authoritative index of implementation reports based on specification tests.

**Comment by theRealImy** [comment]
Preliminary work has been done by the SolidOS team by collecting a list of Solid Apps and libs (initially for other purposes). See v2.0 here: https://solidproject.solidcommunity.net/Team/dpop-migration/
This list is a merge of apps from website and other locations.

**Comment by michielbdejong** [comment]
FWIW, I added a link to the features matrix in its current location, we can update the link when it moves to a new space: https://github.com/solid/solidproject.org/pull/690/files#diff-9ae4de4fb32f674794fb35322200e848da2481e72a2387726c5571b39d9fb253R25

**Comment by michielbdejong** [comment]
Let's try to work together as a peaceful community, and avoid getting a competition between the test suite panel and the solid team where we set up two spaces instead of one. That would be particularly awkward for @csarven and @bourgeoa who are members of both.

**Comment by RubenVerborgh** [comment]
@michielbdejong I'm afraid none of that is particularly relevant. We're talking about all kinds of libraries and code here, servers only being a small part.

**Comment by jaxoncreed** [comment]
Has this been completed? Is there a place where implementations are listed?

**Comment by timea-solid** [comment]
A couple of meetings ago we decided to mention this on the website. Still a TODO
