### ISSUE TITLE
Repositories to be moved

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/team#24]
As per https://github.com/solid/team/issues/22, this issue tracks all repositories that need to be moved.

# SolidOS / Mashlib projects
@theRealImy Are you willing to take the lead in this move? We can use https://github.com/solidos
- [x] https://github.com/solid/mashlib @theRealImy
- [x] https://github.com/solid/solidos @theRealImy
- [x] https://github.com/solid/activitystreams-pane @theRealImy
- [x] https://github.com/solid/chat-pane @theRealImy
- [x] https://github.com/solid/contacts-pane @theRealImy
- [x] https://github.com/solid/data-kitchen @theRealImy
- [x] https://github.com/solid/demo-notes @theRealImy
- [x] https://github.com/solid/folder-pane @theRealImy
- [x] https://github.com/solid/form-playground @theRealImy
- [x] https://github.com/solid/issue-pane @theRealImy
- [x] https://github.com/solid/markdown-pane @theRealImy
- [x] https://github.com/solid/meeting-pane @theRealImy
- [x] https://github.com/solid/money-pane @theRealImy
- [x] https://github.com/solid/pane-registry @theRealImy
- [x] https://github.com/solid/profile-pane @theRealImy
- [x] https://github.com/solid/project-pane @theRealImy
- [x] https://github.com/solid/solid-logic @theRealImy
- [x] https://github.com/solid/solid-pane-source @theRealImy
- [x] https://github.com/solid/solid-panes @theRealImy
- [x] https://github.com/solid/solid-tutorial-rdflib.js @theRealImy
- [x] https://github.com/solid/solid-ui @theRealImy
- [x] https://github.com/solid/solidos-module-interface @theRealImy
- [x] https://github.com/solid/source-pane @theRealImy
- [x] https://github.com/solid/userguide @theRealImy

## Node Solid Server and its authentication libs
@RubenVerborgh has created issues in all of the following
- [x] https://github.com/solid/node-solid-server
- [x] https://github.com/solid/acl-check
- [x] https://github.com/solid/jose
- [x] https://github.com/solid/keychain
- [x] https://github.com/solid/kvplus-files
- [x] https://github.com/solid/node-solid-ws
- [x] https://github.com/solid/oidc-auth-manager
- [x] https://github.com/solid/oidc-op
- [x] https://github.com/solid/oidc-rp
- [x] https://github.com/solid/oidc-rs
- [x] https://github.com/solid/solid-auth-client
- [x] https://github.com/solid/solid-auth-oidc
- [x] https://github.com/solid/solid-multi-rp-client

## Independent Test Suite for Solid
@bourgeoa Could you take the lead? I suggest a new organization to bundle all of the below.

- [x] https://github.com/solid/test-suite @bourgeoa
- [x] https://github.com/solid/solid-crud-tests @bourgeoa
- [x] https://github.com/solid/monetization-tests @bourgeoa
- [x] https://github.com/solid/web-access-control-tests @bourgeoa
- [x] https://github.com/solid/webid-provider-tests @bourgeoa 

## Inrupt-led projects
- [x] https://github.com/solid/access-control-policy @matthieubosquet
- [x] https://github.com/solid/access-token-verifier @matthieubosquet
- [x] https://github.com/solid/conformance-test-harness @edwardsph
- [x] https://github.com/solid/eslint-config-base @matthieubosquet
- [x] https://github.com/solid/solid-oidc-tests @acoburn
- [x] https://github.com/solid/specification-tests @edwardsph
- [x] https://github.com/solid/test-idp @edwardsph

## Various personal projects
@RubenVerborgh has created issues in all of the following
- [x] https://github.com/solid/arduino-solid-server
- [x] https://github.com/solid/datacommons-solid
- [x] https://github.com/solid/folder-table
- [x] https://github.com/solid/food-allergy
- [x] https://github.com/solid/github-solid
- [x] https://github.com/solid/gitter-solid
- [x] https://github.com/solid/msgraph-solid
- [x] https://github.com/solid/solid-auth-fetcher
- [x] https://github.com/solid/solid-cli
- [x] https://github.com/solid/solid-email
- [x] https://github.com/solid/solid-node-client
- [x] https://github.com/solid/solid-notifications
- [x] https://github.com/solid/solid-rest
- [x] https://github.com/solid/solid-sign-up
- [x] https://github.com/solid/solid-signin-ui
- [x] https://github.com/solid/solid-takeout-import
- [x] https://github.com/solid/solid-tutorial-angular
- [x] https://github.com/solid/solid-tutorial-pastebin
- [x] https://github.com/solid/webmonetization

**Comment by RubenVerborgh** [comment]
Thank you, @theRealImy, that was super fast!

**Comment by bourgeoa** [comment]
As you may now the move from solid to SolidOS organization did not went as well as expected. Links to icons stored in solid/solid-ui gh-pages were lost and all public and private server (NSS or CSS) using a version of mashlib prior to 1.8.2 are not functional.

This is an unforeseen situation but not a fair one for users.
- Reverting solid-ui temporarily to solid organisation was not possible @theRealImy and I were not owner on solid organization.
  @RubenVerborgh @timbl could you make @bourgeoa and @theRealImy owner on solid organization
- to resolve this we need to recreate part of solid-ui in https://solid.github.io/solid-ui/.... and find a way to lock any new update on https://github.com/solid/solid-ui afterwards.

**Comment by RubenVerborgh** [comment]
@bourgeoa Shall we create an empty `solid-ui` repository under `/solid`, where (only) the assets can be placed?
And can the source code be adjusted such that it uses local assets?

**Comment by theRealImy** [comment]
@RubenVerborgh I like the suggestion -> lets try it.

**Comment by RubenVerborgh** [comment]
At https://github.com/solid/solid-ui; @theRealImy and @theRealImy are admins.

**Comment by kjetilk** [comment]
I saw that user-stories have been moved and archived, even though it is not on the list, and I don't remember that having been discussed. Even though we haven't treated people's user stories with appropriate respect, they are are there as a low-threshold way of making contributions, and as recent as this month, they have been mentioned in the [contribution guide](https://github.com/solid/specification/blob/main/CONTRIBUTING.md#contributions-at-source-repository). Let's not get overzealous about these moves and start to break things!

**Comment by RubenVerborgh** [comment]
> I saw that user-stories have been moved and archived, even though it is not on the list,

I did a sweep for old/inactive but in-scope repositories on `/solid`, and given that https://github.com/solid/user-stories hadn't been touched in 2 years, I assumed it was inactive.

> Let's not get overzealous about these moves and start to break things!

Certainly not, thanks for the sharp eye. Moved it back to https://github.com/solid/user-stories

**Comment by acoburn** [comment]
> I suggest that all test repos should be under the solid-contrib org

The Solid-OIDC tests have already moved once. I would like to avoid too many moves, especially as this location is part of the Solid-OIDC specification (and that link is currently broken).

I will bring this up at next week's Authentication panel meeting. I think it would be more sensible to move the tests into the `solid/solid-oidc` repository itself and serve that app from the corresponding GH Pages location. This way we will have a more stable URL.

**Comment by RubenVerborgh** [comment]
All done, thanks for your help!
