### ISSUE TITLE
Where is the official list of Solid Team members?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/team#27]
I expected them to be on https://github.com/solid/process but could not find them there.

For instance Oz is here: https://github.com/solid/process/blob/f6add896cd5389bfa3c345e30ca20091ae5be964/code-of-conduct.md but not listed anywhere else as far as I can see.

It's crucial to get this right for repo permissions.

**Comment by kjetilk** [comment]
I would wish for https://solidproject.org/team to contain that list, but it would clearly require an effort to maintain.

**Comment by csarven** [comment]
Join administrators.md, DEI Team, creators.md, editors.md, system-operators.md

Probably not librarians.md and stakeholders.md.

Aside: "DEI Team" should probably be renamed to deit.md.

**Comment by RubenVerborgh** [comment]
Also librarians and stakeholders should probably not be here; incomplete.

**Comment by VirginiaBalseiro** [comment]
creators.md is outdated compared to https://solidproject.org/team

**Comment by csarven** [comment]
We can consolidate the differences. I suggest to continue to use/update creators.md as 'source' for the time being and find a way for all individuals listed in those documents to appear under solidproject.org/team. It may be simpler to have a single team.md with sections for each role.

**Comment by VirginiaBalseiro** [comment]
https://github.com/solid/process/pull/282

**Comment by timea-solid** [comment]
We worked on updating the lists here: https://github.com/solid/team/issues/33 and streamline it here https://github.com/solid/team/issues/34
We will talk in the solid meeting about librarians and stakeholders and make a separate ticket if need be.
