### ISSUE TITLE
Updating Github Teams

### ISSUE THREAD

**Issue by jaxoncreed** [solid/team#33]
As discussed in the meeting, here are the updates to the team memberships. This is a jumping off point. Feel free to comment if you think any of the suggestions should be different.

Administrators:
 - Currently: @justinwb , @timbl , @bourgeoa , @timea-solid , @MarrelleBailey, @jaxoncreed 
 - Suggestion: Remove @MarrelleBailey (no longer works closely with Solid)

Code of Conduct Committee
 - Currently: @csarven , @bourgeoa , @VirginiaBalseiro 
 - Suggestion: Add @oolivo to Code of Conduct Committee

Creators
 - Currently @Vinnl , @kay-kim , @KyraAssaad , @VirginiaBalseiro , @jeff-zucker, @TallTed  
 - Suggestion: There may be future suggestions proposed by @jeff-zucker 

DIET
 - Currently @csarven , @KyraAssaad , @Hindia , @VirginiaBalseiro , @ewingson , @jeff-zucker , @MarrelleBailey 
 - Suggestion: Remove @MarrelleBailey (no longer works closely with Solid)

Editors
 - Currently @kjetilk , @csarven , @barath , @RubenVerborgh , @dmitrizagidulin , @timbl 
 - Suggestion: No Change

Panels
 - Currently Many members depending on panel membership
 - Suggestion Let eat panel decide membership

System Operators
 - @michielbdejong , @ericprud , @bourgeoa 
 - Suggestion: Add @jaxoncreed  and @justin and change the name of this team to "solidcommunity.net maintainers"

**Comment by VirginiaBalseiro** [comment]
Actually, I need to be kept as a creator because of the translation project.

**Comment by VirginiaBalseiro** [comment]
@oolivo needs to be added to CoCC

**Comment by michielbdejong** [comment]
> System Operators
> [...]
> Do further research to find the purpose of this team

I think this was about operating the various domains that are related to (and important for) the project stay up and available as much as possible (or at least to our best efforts).
* [solidproject.org](https://solidproject.org/)
* [solidcommunity.net](https://solidcommunity.net/)
* [solidservers.org](https://solidservers.org/)
* etc ...

I think @jaxoncreed and @justinwb also play a critical role in this in practice, so they should be listed here too probably.

**Comment by bourgeoa** [comment]
> System Operators

> I think this was about operating the various domains that are related to (and important for) the project, so they stay up and available as much as possible (or at least to our best efforts).

To my knowledge the group was only in charge of operating the solidcommunity.net Solid server.
I also think that @jaxoncreed and @justinwb should be part of the group.

I think we need something else to describe the activity related to management of hosting domain name, and server. This seem to be done by @justinwb only.

**Comment by RubenVerborgh** [comment]
Let's also not over-bureaucratize. These groups have been used as recognition in the past, but their contemporary goal is related to the more pragmatic goal of access management. Recognition is important, but let's do that elsewhere; the minimal setup here is to make sure people only have the permissions they need to do their job.

**Comment by bourgeoa** [comment]
I think we all agree that these groups are only related to access management and not recognition.
This is the intent of this solid-team action.

**Comment by timea-solid** [comment]
The domain renewal process is also discussed: https://github.com/solid/process/issues/308 which involves different roles too. Do we add those roles here too or?

**Comment by jaxoncreed** [comment]
Okay I am making the changes now.

**Comment by timea-solid** [comment]
@TallTed do you want to be an official editor and have the appropriate gitHub right in the Solid organization?

**Comment by TallTed** [comment]
@timea-solid — If what I've been doing classes me as a creator, sure.

**Comment by jeff-zucker** [comment]
There is [extensive discussion](https://github.com/solid/process/issues/314) of who might do what in regard to creators and a meeting should happen soonish with Oz who is also interested.

**Comment by timea-solid** [comment]
Ok I think this is now the most up to date situation. We can close this issue and for any future changes please make a new ticket.

**Comment by timea-solid** [comment]
@TallTed please accept the invite to be a creator and update your description as you like for the website on this PR (which can edit after you accept): https://github.com/solid/solidproject.org/pull/766

**Comment by TallTed** [comment]
@timea-solid — For future invitations... You might point people directly to [the organizations page](https://github.com/settings/organizations) (which is individualized to the viewer) where the invitation waits for approval. It took me a while to figure out where it was hiding!
