### ISSUE TITLE
Manage access to social media accounts, domain name registrations, etc for Solid Team

### ISSUE THREAD

**Issue by michielbdejong** [solid/team#40]
On 3 October 2022, we (Solid Team) needed to update the solidproject.org domain name registration, and were not able to do so well, due to a lack of effective password management (through 1Password or otherwise).

On 11 May 2023, the banner of the project_solid Twitter account needed to be updated, and again, it was not clear who was able to action this.

On Thursday we ran into a situation again where we wanted to update who the project_solid Twitter/X account follows, and in the end we needed to go through various people to get this actioned.

If there still is a 1Password account then let's make sure the right people (can be a subset of Solid Team) have access to it.
If the 1Password account that we used for this in the past has expired or needs payment, then let's renew it.

And as a follow-up once this is done, if we notice any assets that fall under the Solid Team's responsibility are not manageable through the 1Password account, then let's make sure we add them.

See also https://github.com/solid/process/issues/308 where it seems this problem was partially addressed but apparently not resolved entirely.

**Comment by jeswr** [comment]
Closed as ODI is now taking care of these accounts - please reach out if there are any concerns.
