### ISSUE TITLE
Update team members

### ISSUE THREAD

**Issue by VirginiaBalseiro** [solid/team#44]
As per Responsibilities (https://github.com/solid/team/pull/39/files#diff-7519aafe48e2ca696efec05f9bba9c9037718d4b4f9f9f032a666af5f9a3bc84):

> Solid Team members must attend Solid Team meetings on a semi-regular basis. They are also expected to participate in Solid Team activities to some degree.

And Membership (https://github.com/solid/team/pull/39/files#diff-7519aafe48e2ca696efec05f9bba9c9037718d4b4f9f9f032a666af5f9a3bc84): 

> Solid Team Members may also be expelled by the Solid Director, by Team decision, or may resign.

Some individuals listed on the members list have been inactive for quite some time, haven't attended meetings or engaged in chat, some for well over a year or more. Tagging the following team members to re-confirm their commitment. 

If there is interest to continue being a member of the Solid Team, please state in what capacity you will engage and which tasks you will be carrying out. If you're unable to attend meetings for whatever reason, please state so as well. 

If no response, inactive members will be removed from the team by 30/01/2024. 

* Kay Kim @kay-kim 
* Kelly O'Brien @inruptkelly
* Justin Bingham @justinwb 
* Kjetil Kjernsmo @kjetilk 
* Nicolas Seydoux @NSeydoux
* Barath Raghavan @barath 
* Dmitri Zagidulin @dmitrizagidulin 
* Vincent Tunru @Vinnl

**Comment by oolivo** [comment]
Do creators needs to attend meetings? For example, Kay has made PR's and contributed to initiatives such as the solidproject.org rewrite and tutorial updates. But does not attend meetings. Does that still qualify as inactive? In Kay's case, I don't think it matters one way or another as she will only contribute when asked to as part of her job. But in general it would be useful to write down the criteria for what constitutes "Active" membership so that everyone is aware.

**Comment by VirginiaBalseiro** [comment]
> Do creators needs to attend meetings? For example, Kay has made PR's and contributed to initiatives such as the solidproject.org rewrite and tutorial updates. But does not attend meetings. Does that still qualify as inactive? In Kay's case, I don't think it matters one way or another as she will only contribute when asked to as part of her job. But in general it would be useful to write down the criteria for what constitutes "Active" membership so that everyone is aware.

As stated above:

> As per Responsibilities (https://github.com/solid/team/pull/39/files#diff-7519aafe48e2ca696efec05f9bba9c9037718d4b4f9f9f032a666af5f9a3bc84):

> Solid Team members must attend Solid Team meetings on a semi-regular basis. They are also expected to participate in Solid Team activities to some degree.

**Comment by kjetilk** [comment]
Thank you for bringing this up @VirginiaBalseiro . I very much appreciate your leadership, and please accept my apologies for not responding sooner. Technologies based on RDF to enhance human agency for individuals and collaboration has been a major part of my life for 25 years, so it isn't at all easy for me to walk away from this project. But I'm so disappointed with where Solid has gone that I suppose I will not be engaged at the level I was. I am still subscribed to many repos in a participation and @-mention basis, as well as being on the CG mailing list. I sincerely hope that you will be able to put Solid on a better path, but I don't feel that I can contribute anymore.

**Comment by VirginiaBalseiro** [comment]
@kjetilk very sad to see you go, and I hope you will come back in the future.

**Comment by kjetilk** [comment]
Thank you, @VirginiaBalseiro !

**Comment by melvincarvalho** [comment]
> RDF to enhance human agency for individuals and collaboration has been a major part of my life for 25 years, so it isn't at all easy for me to walk away from this project. But I'm so disappointed with where Solid has gone

Thanks for your contributions @kjetilk 

I sympathize very strongly with everything that you say.  However, I'm not quite ready to give up on Solid, and I see in there still lots of potential (perhaps somewhat buried).

Is there anything concrete that you think could have been done better, or that could be done better now?

The feedback that I have personally had in the last few years, is that Solid could do better terms of things like diversity, inclusion and outreach.  But your insights over 25 years, either technical or other, I think could be quite valuable to those of us that remain with Solid.

**Comment by jeswr** [comment]
Closing for same reason as #40, and also want to say a massive thankyou to all who have worked on the Solid Team - your work is greatly appreciated!
