### ISSUE TITLE
Move Solid Apps 

### ISSUE THREAD

**Issue by MarrelleBailey** [solid/team#5]
- [ ]  Agree that the target location is the Forum (tentatively discussed need official confirmation) – **Action item done by: by May 7, 2021**

- [ ]  What notice needs to be given – **Decided no later than the end of Solid Team Meeting May 12, 2021**
- [ ]  Notice to the community

- [ ] Get approval from the Solid Team 

- [ ] Actually write and post a note to the community – Determined during the Solid Team Meeting

- [ ] Do the transfer of the applications

**Comment by jaxoncreed** [comment]
If this refers to applications that were once in the github.com/solid organization, then this task is complete. Closing for now.
