### ISSUE TITLE
Design the new Solid Application System to the Forum

### ISSUE THREAD

**Issue by MarrelleBailey** [solid/team#6]
- Determine a **date** for change
- Notify the community about the changes on various channels (Forum, Twitter, Gitter, and possibly LinkedIn)

**Comment by MarrelleBailey** [comment]
Designed and have a demo: May 7, 2021
Reviewed Due: May 10, 2021

**Comment by jaxoncreed** [comment]
Marked as done in Solid Team Action Items. Closing.
